---
title: "Immunizing the Economy: A Causality Discussion on Vaccines and Economic Recovery"
subtitle: "Inmunizando a la Economía: Una Discusión de Causalidad Sobre Vacunas y Reactivación Económica"
author: "Daniel Hernan Sánchez Pazmiño"
format: 
  html: default
editor: source
execute:
  echo: false
  message: false
  warning: false
  cache: true
---

```{r}
# Setup options, for the whole document;
# | label: setup
# | include: false

# Load me my libraries

library(modelsummary) # Regression tables
library(tidyverse) # Tidyverse
library(patchwork) # Multiple plots in one pane
library(fixest) # Fixed Effects OLS
library(openxlsx) # Manage XL stuff
library(fwildclusterboot) # Wild bootstrap tests

# Load me my data

df<-read.csv('../data/df.csv')

```


# Abstract

The COVID-19 pandemic severely disrupted economic activity worldwide. In Ecuador, the pandemic found an epicenter in the city of Guayaquil during April 2020, where the excess death rate skyrocketed to almost 700%. However, in mid-2021, Ecuador had a glimpse of hope again as the vaccination process turned extremely effective and under a hundred days half of the country’s population was inoculated. While since then excess deaths have remained at all-time lows in the pandemic era, the Ecuadorian economy remains weakened. This paper discusses a causal effect of vaccination on economic recovery by implementing a two-way fixed effects difference-in-differences estimator on a repeated cross section of Ecuador 2020-2021 at the province-level. Evidence is found that provinces with apparent vaccine-hesitant populations see about 25% less business creation than provinces with openness to vaccination. This finding stresses the importance of fostering vaccination among populations in a country, especially if booster shots are necessary in the future. This effect is found by leaving out the creation of SAS (Sociedad de Acciones Simplificada) businesses, a new firm legal figure introduced to the country in mid-May, which prompted the creation of many new formal businesses due to the reduction of entry costs. Only minimal evidence of differential prior trends is found, which supports the existence of causality. Finally, other estimation methodologies are proposed to identify a more precise causal effect of vaccination on economic activity.

# Resumen

La pandemia del COVID-19 interrumpió severamente la actividad económica mundial. En Ecuador, la pandemia encontró un epicentro en la ciudad de Guayaquil en abril del 2020, en donde la tasa de mortalidad en exceso llegó a casi el 700%. Sin embargo, en la mitad del 2021 el Ecuador tuvo un destello de esperanza cuando el proceso de vacunación se tornó extremadamente efectivo y en menos de cien días más de la mitad de población se inmunizó completamente. Aunque desde ese momento las muertes en exceso se mantienen en mínimos históricos en la era de la pandemia, la economía ecuatoriana se mantiene debilitada. Este artículo discute un efecto causal de la vacunación en la reactivación económica utilizando un estimador diferencia-en-diferencias de efectos fijos de doble vía en una sección transversal repetida del Ecuador 2020-2021 a nivel provincial. Se encuentra evidencia de que provincias con poblaciones aparentemente resistentes a la vacunación ven aproximadamente un 25% menos de creación de empresas, en comparación a provincias más abiertas a la vacunación. Este hallazgo resalta la importancia de fomentar la vacunación en las poblaciones de un país, especialmente si dosis de refuerzo se requieren en el futuro. Este efecto se encuentra eliminando la creación de las empresas SAS (Sociedad de Acciones Simplificada), una figura legal de compañía introducida en el país en la mitad del 2020 que ocasionó la creación de nuevas firmas debido a la reducción considerable de costos de entrada. Se encuentra evidencia mínima de tendencias previas no similares, lo que apoya a la existencia de causalidad. Finalmente, se proponen otras metodologías de estimación para identificar un efecto causal más preciso de la vacunación en la actividad económica.

# Introduction

Although the 21st century is still far from over, COVID-19 will necessarily be reminded as one of the most important happenings of the time. The changes that the pandemic has brought about have been long-lasting, as the virus which originally emerged in China by late 2019 has had effects still suffered by the time this article was written. In April 2020, the IMF predicted that the economic effects of the pandemic would be the greatest since the Great Depression [@IMF.April2020]. By October 2020, the IMF revised down their projections of world economic growth and the pandemic accumulated over a million deaths to COVID-19, proving to be a worse crisis than what it was initially expected. It was understood that both the health risks posed by COVID-19 and the lockdown policy enacted by the world's governments had greatly hampered economic conditions around the world, especially in the Western Hemisphere [-@IMF.Oct2020].

Ecuador barely escaped economic and social chaos by securing an agreement with the IMF in 2020 worth 6.5 billion dollars after facing terrible consequences due to high public debt and the precipitous fall of oil prices [@IMF.Oct2020.Art]. However, the Ecuadorian economy was still expected to shrink by 11% in 2020 and its unemployment rate was expected to increase in `r 8.1 - 3.8` percentage points relative to 2019 [@IMF.Oct2020]. Guayas became the COVID-19 epicenter in Ecuador with a 900% excess deaths rate [@Naranjo.2020] and with its capital Guayaquil becoming an international attention center due to the extreme humanitarian crisis caused by the COVID-19 impact [@Zibell.2020]. 

However, by 2021 new hope surfaced as newly-developed COVID-19 vaccines received authorities approval and started to be massively distributed around the world by April 2021. The actual economic downturn in 2020 was smaller for both Ecuador and the global economy as well, which encouraged hopes for the coming year. The IMF revised its 2021 projections upward as vaccine rollouts developed in the United States and other developed economies [-@IMF.April2021]. However, on the developing world and notably in Ecuador vaccine distribution became increasingly unequal, as top government officials and private agents received their first vaccine doses before those that actually needed them [@Taj.2021]. In Ecuador the immunization process was initially slow and corrupt: the Ministry of Health's mother and two well-connected TikTok influencers received a vaccination dose before some first-line workers were even eligible to receive one [@Machado.2021; @Sandoval.2021]. Corruption in vaccination and public health contracting played a key role in the resignations and removals of four Ministries of Health between March 2020 and April 2021. 

Yet once again Ecuador became the center of international attention in the second half of 2021 as its sovereign bonds provided the best returns in the world after the possession of economically-liberal President Guillermo Lasso [@Vizcaino.2021]. The Lasso Administration was able to immunize over half of the country's population in 100 days after his possesion in May 24th, which may have converted Lasso into one of the most popular presidents in the region by October 2021 [@Hurtado.2021]. The new Administration's economic agenda promised economic recovery through investment-friendly policy [@Madrid.2021], even marketing the massive vaccination plan as an initial step for recovery after the pandemic shock [@Brik.2021].

The Ecuadorian economy grew 4.2% in 2021 [@BCE.2022], 50% more than the October 2021 IMF projection [-@IMF.Oct2021].The Ecuadorian Central Bank attributes the increases due to important economic gains in the oil, tourism, agriculture and commerce industries, citing the economic effects brought about by the successful vaccine rollout as the main motivator for the internal economic reactivation. However, the statement by the institution may pose an important causal inference issue: even if vaccines have proven to be successful in mitigating COVID-19 infection [@Katella.2022], not much is known about their effect on economic activity. Additionally, the vaccination process may also correlate with other reactivation motivators which may become confounders. Among them stand the `r (78.90/48.52) * 100` % increase in the price of the WTI oil barrel [@MarketWatch.2022] and the loosening of pandemic restrictions which took place after Lasso took office. 

The aim of this paper is to discuss the possibility of a causal effect of COVID-19 vaccination in economic recovery. This is done by implementing a regression-based approach to a difference-in-differences research design to estimate an average treatment effect of vaccine hesitancy in two proxies of economic activity. Province-level data from Ecuador on several economic and demographic indicators published in a monthly basis is used for the econometric analysis, which focuses on the 24 months between January 2020 and December 2021. 